name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
       # with:
         # submodules: true

#    - name: Build
#      run: ./hugo --minify

    - name: Deploy
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
	SCRIPT_MODE: true
      run:
      - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz -o hugo.tar.gz
      - tar xzvvf hugo.tar.gz -C ./    
      - ./hugo 
      - find public/ -type f -exec sed -i 's/_blank">/_blank" rel="noopener">/g' {} +